<?php

$products = [
    ['id' => 1, 'designation' => 'souris', 'categorie' => 'peripherique', 'modele' => 'Logitech13', 'prix' => 38, 'prixBeforePomo' => 50, 'promotion'
    => true, 'image' => 'mouse.png'], ['id' => 2, 'designation' => 'apple watch', 'categorie' => 'technologie', 'modele' => 'Apple Watch SD', 'prix' => 245, 'prixBeforePomo' => 245, 'promotion'
    => false, 'image' => 'applewatch.png'], ['id' => 3, 'designation' => 'laptop', 'categorie' => 'technologie', 'modele' => 'Asus Vivobook', 'prix' => 1850, 'prixBeforePomo' => 2200, 'promotion'
    => true, 'image' => 'computer.png'], ['id' => 4, 'designation' => 'casque audio', 'categorie' => 'peripherique', 'modele' => 'Hyper X Kraken', 'prix' => 99, 'prixBeforePomo' => 180, 'promotion'
    => true, 'image' => 'headphones.png'], ['id' => 5, 'designation' => 'clavier', 'categorie' => 'peripherique', 'modele' => 'The G Lab', 'prix' => 120, 'prixBeforePomo' => 120, 'promotion'
    => false, 'image' => 'keyboard.png'], ['id' => 6, 'designation' => 'smartphone', 'categorie' => 'technologie', 'modele' => 'Samsung Galaxy S20', 'prix' => 850, 'prixBeforePomo' => 1399, 'promotion'
    => true, 'image' => 'phone.png'], ['id' => 7, 'designation' => 'appareil photo', 'categorie' => 'technologie', 'modele' => 'Canon NX ', 'prix' => 2500, 'prixBeforePomo' => 2500, 'promotion'
    => false, 'image' => 'photo.png'], ['id' => 8, 'designation' => 'handspinner', 'categorie' => 'autre', 'modele' => 'Handspinner Blanc', 'prix' => 2, 'prixBeforePomo' => 2, 'promotion'
    => false, 'image' => 'spinner.png'], ['id' => 9, 'designation' => 'tablette', 'categorie' => 'technologie', 'modele' => 'Samsung Tab A8', 'prix' => 634, 'prixBeforePomo' => 899, 'promotion'
    => true, 'image' => 'tablet.png'], ['id' => 10, 'designation' => 'manette', 'categorie' => 'manette', 'modele' => 'Gamecube', 'prix' => 49, 'prixBeforePomo' => 49, 'promotion'
    => false, 'image' => 'gameCubeController.jpg'], ['id' => 11, 'designation' => 'bar led', 'categorie' => 'autre', 'modele' => 'Oraus', 'prix' => 25, 'prixBeforePomo' => 29, 'promotion'
    => true, 'image' => 'led.jpg'], ['id' => 12, 'designation' => 'laptop', 'categorie' => 'technologie', 'modele' => 'LG Gram 16', 'prix' => 1200, 'prixBeforePomo' => 1800, 'promotion'
    => true, 'image' => 'lgGram.jpg'], ['id' => 13, 'designation' => 'laptop', 'categorie' => 'technologie', 'modele' => 'Mac Book Pro 13', 'prix' => 1566, 'prixBeforePomo' => 2200, 'promotion'
    => true, 'image' => 'macBookPro13.jpg'], ['id' => 14, 'designation' => 'manette', 'categorie' => 'manette', 'modele' => 'PS5 Cobalt Blue', 'prix' => 59, 'prixBeforePomo' => 59, 'promotion'
    => false, 'image' => 'ps5CobaltBlue.webp'], ['id' => 15, 'designation' => 'console', 'categorie' => 'technologie', 'modele' => 'Steam Deck', 'prix' => 500, 'prixBeforePomo' => 500, 'promotion'
    => false, 'image' => 'steamDeck.jpg'], ['id' => 16, 'designation' => 'console', 'categorie' => 'technologie', 'modele' => 'Switch Lite Animal Crossing', 'prix' => 299, 'prixBeforePomo' => 299, 'promotion'
    => false, 'image' => 'SwitchLiteCrossing.jpg'], ['id' => 17, 'designation' => 'manette', 'categorie' => 'manette', 'modele' => 'Xbox Series XS Shadow Gold', 'prix' => 54, 'prixBeforePomo' => 69, 'promotion'
    => true, 'image' => 'xboxShadowSeriesXSGold.jpg'], ['id' => 18, 'designation' => 'bureau', 'categorie' => 'autre', 'modele' => 'Ultimate Gaming Erus', 'prix' => 780, 'prixBeforePomo' => 899, 'promotion'
    => true, 'image' => 'bureau.jpg'], ['id' => 19, 'designation' => 'bureau', 'categorie' => 'autre', 'modele' => 'Angle Master Erus', 'prix' => 900, 'prixBeforePomo' => 970, 'promotion'
    => true, 'image' => 'bureau2.webp'], ['id' => 20, 'designation' => 'casque audio', 'categorie' => 'peripherique', 'modele' => 'Razer Nari Ultimate', 'prix' => 150, 'prixBeforePomo' => 150, 'promotion'
    => false, 'image' => 'razerNariUltimate.jpg'], ['id' => 21, 'designation' => 'console', 'categorie' => 'technologie', 'modele' => 'PS5', 'prix' => 450, 'prixBeforePomo' => 549, 'promotion'
    => true, 'image' => 'PS5.webp'], ['id' => 22, 'designation' => 'console', 'categorie' => 'technologie', 'modele' => 'Xbox Series X', 'prix' => 479, 'prixBeforePomo' => 599, 'promotion'
    => true, 'image' => 'xboxSeriesX.webp'], ['id' => 23, 'designation' => 'ecouteur', 'categorie' => 'peripherique', 'modele' => 'Air Pods Pro', 'prix' => 89, 'prixBeforePomo' => 120, 'promotion'
    => true, 'image' => 'airPodsPro.jpg'], ['id' => 24, 'designation' => 'casque VR', 'categorie' => 'technologie', 'modele' => 'Meta Quest 2', 'prix' => 350, 'prixBeforePomo' => 599, 'promotion'
    => true, 'image' => 'Quest2.webp'], ['id' => 25, 'designation' => 'smartphone', 'categorie' => 'technologie', 'modele' => 'Xiaomi Redmi Note 13', 'prix' => 499, 'prixBeforePomo' => 799, 'promotion'
    => true, 'image' => 'xiaomiRedmiNote13.jpg'], ['id' => 26, 'designation' => 'figurine', 'categorie' => 'autre', 'modele' => 'POP Naruto Kiba & Hakamaru', 'prix' => 15, 'prixBeforePomo' => 15, 'promotion'
    => false, 'image' => 'popKibaHakamaru.jpg'], ['id' => 27, 'designation' => 'figurine', 'categorie' => 'autre', 'modele' => 'POP Marvel She Hulk', 'prix' => 15, 'prixBeforePomo' => 15, 'promotion'
    => false, 'image' => 'popSheHulk.jpg'], ['id' => 28, 'designation' => 'manette', 'categorie' => 'manette', 'modele' => 'Switch Pro', 'prix' => 45, 'prixBeforePomo' => 49, 'promotion'
    => true, 'image' => 'switchPro.webp'], ['id' => 29, 'designation' => 'souris', 'categorie' => 'peripherique', 'modele' => 'Razer Basilisk X HyperSpeed', 'prix' => 120, 'prixBeforePomo' => 120, 'promotion'
    => false, 'image' => 'razerBasilisk.jpg'], ['id' => 30, 'designation' => 'clavier', 'categorie' => 'peripherique', 'modele' => 'Steelseries Apex Pro', 'prix' => 219, 'prixBeforePomo' => 250, 'promotion'
    => true, 'image' => 'steelseriesApex.jpg']
];
